apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Application }}-dc
spec:
  replicas: 3
  selector:
    app: {{ .Application }}
  template:
    metadata:
      labels:
        app: {{ .Application }}
    spec:
      serviceAccountName: {{ .Application }}-sa
      containers:
      - name: {{ .Application }}
        env:
        - name: test
          value: test
        image: {{ .Application }}:latest
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/v1/sys/info/isalive
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 55
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/v1/sys/info/isalive
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
