kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-view
subjects:
  - kind: User
    name: system:serviceaccount:{{ .Project }}-{{ .Env }}
    namespace: {{ .Project }}-{{ .Env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
