apiVersion: batch/v1
kind: Job
metadata:
  name: trackmate-dev-fail-sync-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    #comment this out if you want to leave the job/pod that is created for troubleshooting
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: trackmate-sa
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#cicd-committee", \"text\": \"trackmate app sync Failed!\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2
