apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/apps/namespace-cicd/base
  - ../../../manifests/apps/rbac/base
  - ../../../manifests/tekton/resources/base
  - ../../../manifests/tekton/task/base{{range .Items}}
  - ../../../manifests/tekton/pipelines/{{ .Application }}/base{{end}}  
namespace: {{ .Organization }}-{{ .Project }}-cicd
