apiVersion: v1
kind: ServiceAccount
metadata:
  name:  serviceaccount-dev
imagePullSecrets:
- name: image-pull-secret
secrets:
  - name: quay-creds
  - name: git-basic
  - name: sonarqube
  - name: argocd-git-basic
