kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Project }}-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Project }}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
