---
apiVersion: triggers.tekton.dev/v1alpha1 
kind: EventListener 
metadata:
  name: eventlistener-dev
spec:
  serviceAccountName: serviceaccount-dev
  triggers:
  - name: pipeline-trigger-dev
    bindings: 
      - ref: trigger-binding-dev
    template: 
      ref: trigger-template-dev
