namePrefix: trackmate-
commonLabels:
  app: trackmate
resources:
  - git-http-secret.yaml
  - pipeline-resource-git-infra-http.yaml
  - pipeline-resource-git-http.yaml
  - pipeline-role.yaml
  - smtp-auth.yaml
  - notify-slack-webhook-secret.yaml
  
