apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/apps/rbac/base/
  {{range .Items}}- ../../../manifests/apps/{{ .Env }}/{{ .Application }}/base
  {{end}}
namespace: {{ .Project }}-{{ .Env }}
resources:
  - namespace/namespace.yaml
  - namespace/limit-range.yaml
  - namespace/resource-quota.yaml
  - namespace/service-account-role-binding.yaml
