apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerBinding 
metadata:
  name: trigger-binding-dev
spec:
  params: 
  - name: git-repo-url
    value: $(body.repository.links.clone[0].href)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.changes[0].toHash)
  - name: git-actor-name
    value: $(body.actor.displayName)
  - name: git-actor-email
    value: $(body.actor.emailAddress)