apiVersion: triggers.tekton.dev/v1alpha1 
kind: EventListener 
metadata:
  name: event-listener-uat
spec:
  serviceAccountName: {{ .Project }}-pipeline
  triggers:
  - bindings: 
    - name: {{ .Project }}-trigger-binding-uat
    template: 
      name: {{ .Project }}-trigger-template-uat
