apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    persistentvolumeclaims: "9"
    services: "50" 
    pods: "50"

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-scoped
spec:
  hard:
    requests.memory: 5Gi
    requests.cpu: 4000m
    limits.memory: 5Gi
    limits.cpu: 4000m
  scopes:
  - NotTerminating