apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: veracode-scanner
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: patch
    tekton.dev/displayName: "veracode client scanner for java"
spec:
  params:
    - name: VERACODE_API_ID
      type: string
    - name: VERACODE_API_SECRET
      type: string
    - name: JAR_FILE
      type: string
    - name: PROJECT_NAME
      type: string
    - name: ISSUE_DETAILS
      type: string
    - name: SUMMARY_DISPLAY
      type: string
    - name: SUMMARY_OUTPUT
      type: string
    - name: JSON_DISPLAY
      type: string

  workspaces:
    - name: source

  steps:
    - name: scan
      image: robermar2/ultra-cli-veracode-scanner:latest
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsUser: 0
      script: |
          java -jar /scanner/pipeline-scan.jar \
          --veracode_api_id "$(params.VERACODE_API_ID)" \
          --veracode_api_key "$(params.VERACODE_API_SECRET)" \
          --file "$(params.JAR_FILE)" \
          --project_name "$(params.PROJECT_NAME)" \
          --fail_on_severity="Very High, High" \
          --fail_on_cwe="80" \
          --issue_details="$(params.ISSUE_DETAILS)" \
          --summary_display="$(params.SUMMARY_DISPLAY)" \
          --summary_output="$(params.SUMMARY_OUTPUT)" \
          --json_display="$(params.JSON_DISPLAY)"
    - name: result-text
      image: robermar2/ultra-cli-veracode-scanner:latest
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsUser: 0
      script: |
          test -f results.txt && cat results.txt
    - name: result-json
      image: robermar2/ultra-cli-veracode-scanner:latest
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsUser: 0
      script: |
          test -f results.json && cat results.json