apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #name of the argocd app
  name: trackmate-cicd
  #apps always in argocd namespace for operator
  namespace: devops-argo
  labels:
    COST-TENANCY: Dedicated
    ORG: 14west
    DEPT: DEVOPS
  annotations:
    # exclude resources creates by tools for app sync status
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    #namespace to place the app
    namespace: 14west-trackmate-cicd
    #cluster to install the app into
    server: 'https://kubernetes.default.svc'
  #the argocd appproject to put this app into
  project: trackmate
  source:
    #path to source in the repo
    path: environments/overlays/cicd
    #repo url
    repoURL: 'ssh://git@code.14west.us:7999/cicd/trackmate.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
