apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    persistentvolumeclaims: "9"
    services: "50" 
    pods: "50"

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-scoped
spec:
  hard:
    requests.memory: 10Gi
    requests.cpu: 6000m
    limits.memory: 10Gi
    limits.cpu: 6000m
  scopes:
  - NotTerminating
