apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "6Mi"
    - type: "Container"
      # it is very import to include a default otherwise builder and deployer pods will not run
      default:
        cpu: "150m"
        memory: "200Mi"
      defaultRequest:
        cpu: "50m"
        memory: "100Mi"
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "3Mi"