apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/apps/rbac/base/{{range .Items}}
  - ../../../manifests/apps/{{ .Application }}/base{{end}} 
namespace: {{ .Organization }}-{{ .Project }}-{{ .Env }}
resources:
  - namespace/namespace.yaml
  - namespace/limit-range.yaml
  - namespace/resource-quota.yaml
  - namespace/service-account-role-binding.yaml
  - argo/post-sync-promote.yaml
  #- argo/post-sync-fail.yaml
patchesJson6902:
  {{range .Items}}
  - path: patches/patch-{{ .Project }}-{{ .Application }}-image.yaml
    target:
      group: apps.openshift.io
      kind: DeploymentConfig
      name: {{ .Application }}-dc
      version: v1
  - path: patches/patch-{{ .Project }}-{{ .Application }}-env.yaml
    target:
      group: apps.openshift.io
      kind: DeploymentConfig
      name: {{ .Application }}-dc
      version: v1
  - path: patches/patch-{{ .Project }}-{{ .Application }}-resources.yaml
    target:
      group: apps.openshift.io
      kind: DeploymentConfig
      name: {{ .Application }}-dc
      version: v1
  - path: patches/patch-{{ .Project }}-{{ .Application }}-replicas.yaml
    target:
      group: apps.openshift.io
      kind: DeploymentConfig
      name: {{ .Application }}-dc
      version: v1
  {{end}} 

  - path: patches/patch-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: {{ .Application }}-{{ .Env }}-promote-
