apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Project }}
  namespace: devops-argo
spec:
  # Project description
  description: devops {{ .Project }}

  # Allow manifests to deploy from these Git repos
  sourceRepos:
  - 'ssh://git@code.{{ .Organization }}.us:7999/cicd/{{ .Project }}.git'

  destinations:
  - namespace: {{ .Organization }}-{{ .Project }}-dev
    server: https://kubernetes.default.svc
  - namespace: {{ .Organization }}-{{ .Project }}-uat
    server: https://kubernetes.default.svc
  - namespace: {{ .Organization }}-{{ .Project }}-prd
    server: https://api.c5.us-east-1.dev.aws.ocp.{{ .Organization }}.io:6443
  - namespace: {{ .Organization }}-{{ .Project }}-cicd
    server: https://kubernetes.default.svc

  roles:
  # A role which provides all access to all applications in the project
  - name: admin
    description: all privs to all projects
    policies:
    - p, proj:{{ .Project }}:admin, applications, *, {{ .Project }}/*, allow
    groups:
    - cluster-admins
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: PersistentVolume
  # - group: 'config.openshift.io'
  #   kind: OAuth

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: ResourceQuota
  # - group: ''
  #   kind: LimitRange
  # - group: ''
  #   kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  # namespaceResourceWhitelist:
  # - group: 'apps'
  #   kind: Deployment
  # - group: 'apps'
  #   kind: StatefulSet

  # Enables namespace orphaned resource monitoring.
  # orphanedResources:
  #   warn: false
