apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-infra-http
spec:
  params:
    - name: url
      value: '{{ .Repos.Cicd }}'
    - name: revision
      value: HEAD
  type: git
