apiVersion: v1
kind: Secret
metadata:
  name:  smtp-auth
type: Opaque
data:
   url: {{ .Smtp.Url }}
   port: {{ .Smtp.Port }}
   user: {{ .Smtp.User }}
   password: {{ .Smtp.Password }}
   tls: {{ .Smtp.Tls }}
