apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-image
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: patch
    tekton.dev/displayName: "patch image"
spec:
  params:
    - name: IMAGE_TAG
      type: string
    - name: GIT_REVISION
      type: string
    - name: GIT_AUTHOR_NAME
      type: string
    - name: GIT_AUTHOR_EMAIL
      type: string
    - name: MANIFEST_FILE
      type: string
    - name: CONTAINER_NAME
      type: string

  resources:
    inputs:
      - {type: git, name: git-source} 
  steps:
    - name: patch-image
      image: robermar2/ultra-cli:latest
      workingDir: /workspace/git-source
      script: |
          #!/usr/bin/env bash
          set -ex
          git config --global user.email "$(params.GIT_AUTHOR_EMAIL)"
          git config --global user.name "$(params.GIT_AUTHOR_NAME)"
          cat > $(params.MANIFEST_FILE) << EOF
          - op: replace
            path: "/spec/template/spec/containers/0/image"
            value: $(params.IMAGE_TAG)
          EOF

          git add $(params.MANIFEST_FILE)

          if [[ $(git status -s | wc -l) -eq 0 ]]; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Patch image from commit $(params.GIT_REVISION)"
          git push -v --set-upstream origin master

          git rev-parse HEAD | tee /tekton/results/revision
          echo -n $(params.IMAGE_TAG) | tee /tekton/results/image_tag
          
  results:
    - name: revision
      description: The git revision to the infra repo
    - name: image_tag
      description: The image_tag applied to the patch
