apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: promote-image
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: replace
    tekton.dev/displayName: "replace image"
spec:
  params:
    - name: FROM_IMAGE_PATCH_FILE
      type: string
    - name: TO_IMAGE_PATCH_FILE
      type: string
    - name: COMMIT_MESSAGE
      type: string

  resources:
    inputs:
      - {type: git, name: git-source} 
  steps:
    - name: ultra-cli
      image: robermar2/ultra-cli:latest
      workingDir: /workspace/git-source
      script: |
          #!/usr/bin/env bash
          set -ex

          if [ ! -f $(params.FROM_IMAGE_PATCH_FILE) ]; then
            echo "$(params.FROM_IMAGE_PATCH_FILE) does not exist"
            exit 1
          fi

          if [ ! -f $(params.TO_IMAGE_PATCH_FILE) ]; then
            echo "$(params.TO_IMAGE_PATCH_FILE) does not exist"
            exit 1
          fi

          cat $(params.FROM_IMAGE_PATCH_FILE) > $(params.TO_IMAGE_PATCH_FILE)
          
          user=$(git log -1 --pretty=format:'%an' | xargs)
          email=$(git log -1 --pretty=format:'%ae' | xargs)
          rev=$(git log -1 --pretty=format:'%H' | xargs)

          git config user.email "$email"
          git config user.name "$user"

          git add $(params.TO_IMAGE_PATCH_FILE)

          if [[ $(git status -s | wc -l) -eq 0 ]]; then
            echo "No changes"
            exit 0
          fi

          git commit -m "$(params.COMMIT_MESSAGE)"
          git push -v --set-upstream origin master