apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterbinding-dev
subjects:
- kind: ServiceAccount
  name: serviceaccount-dev
  namespace: test-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole-dev
