kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-priv
subjects:
  - kind: ServiceAccount
    name: {{ .Application }}-pipeline
    namespace: {{ .Organization }}-{{ .Project }}-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Project }}-pipeline-privileged-role
