apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: trigger-route-dev
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Project }}-event-listener-dev
  tls:
    termination: edge
